Update csm-release-libs.yaml

diff --git a/.github/workflows/csm-release-libs.yaml b/.github/workflows/csm-release-libs.yaml
--- a/.github/workflows/csm-release-libs.yaml
+++ b/.github/workflows/csm-release-libs.yaml
@@ -6,83 +6,62 @@
 #
 #  http://www.apache.org/licenses/LICENSE-2.0
 
-# This workflow is used to release libraries like gobrick, gofsutil etc.
 name: Release Go Client Libraries
 
-# Invocable as a reusable workflow
 on:
   workflow_call:
     inputs:
       version:
         description: 'Version to release (major, minor, patch), ex: 1.0.0'
         required: true
-  workflow_dispatch:
-    inputs:
-      version:
-        description: 'Version to release (major, minor, patch), ex: 1.0.0'
-        required: true
+        type: string
         default: 'none'
-  repository_dispatch: # Triggered from another repo (libs)
-    types: [auto-release-workflow]
 
 jobs:
   build-and-scan:
     name: Build, Scan and Release
     runs-on: ubuntu-latest
     steps:
-      - name: Set version from payload or input
-        run: |
-          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
-            echo "Version from payload: ${{ github.event.client_payload.version }}"
-            echo "VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV
-          elif [[ "${{ github.event.inputs.version }}" != "none" ]]; then
-            echo "Version from input: ${{ github.event.inputs.version }}"
-            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
-          else
-            echo "Invalid version specified. Exiting."
-            exit 1
-          fi
-
       - name: Validate version input
         run: |
-          if [[ "${{ env.VERSION }}" == "none" || ! "${{ env.VERSION }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Invalid version specified: ${{ env.VERSION }}. It must follow major.minor.patch format."
+          if [[ "${{ inputs.version }}" == "none" ]]; then
+            echo "Invalid version specified: ${{ inputs.version }} Must follow major, minor, patch versioning."
             exit 1
           fi
-
       - name: Checkout the code
         uses: actions/checkout@v4
-
       - name: Set up Go
         uses: actions/setup-go@v5
         with:
           go-version: "1.23"
-
       - name: Install dependencies
         run: go mod tidy
-
       - name: Build
         run: go build -v ./...
-
       - name: Run malware scan
         uses: dell/common-github-actions/malware-scanner@main
         with:
           directories: .
           options: -ri
 
+      - name: Delete existing tag in remote
+        run: |
+          git tag -d v${{ inputs.version }} || true
+          git push --delete origin v${{ inputs.version }} || true
+
       - name: Create new tag
         run: |
           git config --global user.name 'github-actions'
           git config --global user.email 'github-actions@github.com'
-          git tag v${{ env.VERSION }}
-          git push origin v${{ env.VERSION }}
+          git tag v${{ inputs.version }}
+          git push origin v${{ inputs.version }}
 
       - name: Create Release
         id: release_notes
         uses: softprops/action-gh-release@v2
         with:
-          tag_name: v${{ env.VERSION }}
-          name: Release v${{ env.VERSION }}
+          tag_name: v${{ inputs.version }}
+          name: Release v${{ inputs.version }}
           draft: true
           prerelease: false
           generate_release_notes: true
@@ -94,5 +73,5 @@ jobs:
         run: |
           git config --global user.name 'github-actions'
           git config --global user.email 'github-actions@github.com'
-          git checkout -b release/v${{ env.VERSION }}
-          git push origin release/v${{ env.VERSION }}
+          git checkout -b release/v${{ inputs.version }}
+          git push origin release/v${{ inputs.version }}
